<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php $_element = $block->getElement() ?>
<?php $_jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $_element->getHtmlId() ?>
<div class="rule-tree">
    <fieldset
        id="<?= $_jsObjectName ?>" <?= $_element->serialize(['class']) ?>
        class="fieldset">
        <legend class="legend"><span><?= $_element->getLegend() ?></span></legend>
        <br>
    <?php if ($_element->getComment()) : ?>
        <div class="messages">
            <div class="message message-notice"><?= $block->escapeHtml($_element->getComment()) ?></div>
        </div>
    <?php endif ?>
    <div class="rule-tree-wrapper">
        <?= $_element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?= $_jsObjectName ?> = new VarienRulesForm(
    '<?= $_jsObjectName ?>',
    '<?= $block->getNewChildUrl() ?>'
);
<?php if ($_element->getReadonly()) : ?>
    <?= $_element->getHtmlId() ?>.setReadonly(true);
<?php endif ?>

});
</script>
