<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php $element = $block->getElement() ?>
<?php $jsObjectName = $block->getFieldSetId() != null ? $block->getFieldSetId() : $element->getHtmlId() ?>
<div class="rule-tree">
    <fieldset
        id="<?= $block->escapeHtml($jsObjectName) ?>" <?= $block->escapeHtml($element->serialize(['class'])) ?>
        class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml($element->getLegend()) ?></span></legend>
        <br>
    <?php if ($element->getComment()) : ?>
        <div class="messages">
            <div class="message message-notice"><?= $block->escapeHtml($element->getComment()) ?></div>
        </div>
    <?php endif ?>
    <div class="rule-tree-wrapper">
        <?= $element->getChildrenHtml() ?>
    </div>
    </fieldset>
</div>
<script>
require([
    "Magento_Rule/rules",
    "prototype"
], function(VarienRulesForm){

window.<?= $block->escapeHtml($jsObjectName) ?> = new VarienRulesForm(
    '<?= $block->escapeHtml($jsObjectName) ?>',
    '<?= $block->escapeHtml($block->getNewChildUrl()) ?>'
);
<?php if ($element->getReadonly()) : ?>
    <?= $element->getHtmlId() ?>.setReadonly(true);
<?php endif ?>

});
</script>
